/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagementHubRouteImport } from './routes/management-hub'
import { Route as IndexRouteImport } from './routes/index'

const ManagementHubRoute = ManagementHubRouteImport.update({
  id: '/management-hub',
  path: '/management-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/management-hub': typeof ManagementHubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/management-hub': typeof ManagementHubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/management-hub': typeof ManagementHubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/management-hub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/management-hub'
  id: '__root__' | '/' | '/management-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagementHubRoute: typeof ManagementHubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/management-hub': {
      id: '/management-hub'
      path: '/management-hub'
      fullPath: '/management-hub'
      preLoaderRoute: typeof ManagementHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagementHubRoute: ManagementHubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
